#!/bin/bash

if [ -z "$1" ] || [ -z "$2" ] || [ -z "$3" ]; then
    echo "Usage: decript <encrypted_file> <output_file> <password>"
    exit 1
fi

openssl enc -aes-256-cbc -d -in "$1" -out "$2" -pass pass:"$3"

echo "File '$1' berhasil didekripsi menjadi '$2'."